apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    workflows.argoproj.io/pod-name-format: v2
  generateName: backfill-bsc-testnet-
  labels:
    submit-from-ui: "false"
    workflows.argoproj.io/workflow-template: bsc-testnet-backfill
    chain: bsc-testnet
  namespace: blockchain-data
spec:
  arguments:
    parameters:
    - name: backfill-from
      value: 49862340000
    - name: backfill-to
      value: 49862340000
  entrypoint: main
  workflowTemplateRef:
    name: bsc-testnet-backfill
